[cz]
  languageCode = "cz"
  languageName = "Čeština"
  # Uncomment for multilingual sites, and move the default content into corresponding sub-folder.
  contentDir = "content/cz"

# Uncomment for multilingual sites, and customize the following config.
[en]
  languageCode = "en"
  languageName = "English"
  contentDir = "content/en"
  title = "Babice caving club"