baseURL = "/"
languageCode = "cs"
title = "Babická speleologická skupina"
theme = "babicka-skupina"
googleAnalytics = ""
paginate = 3

[params]
  subtitle = "Česká speleologická společnost, základní organizace 6-28"
  description = "My site description"
  date_format = "January 2, 2006"

[params.hero]
  textColor = "" # Empty for default color

[params.separator] # Separators between sections on the home page
  show = false

[params.fa] # Font Awesome options
  version = "5.7.2"
  integrity = "sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"

[params.posts]
  showAuthor = true
  showDate = true
  showTags = true
  dateFormat = "Monday, Jan, 2006"

[params.contact] # Contact info
  email = "info@speleobabice.cz"
  phone = "+420 602 710 343"
  address = "Spešov 116, 679 02 Spešov"

[params.social]
  facebook = "https://facebook.com/john"
  instagram = "https://instagram.com/john"
  rss = "feed.xml"

[params.copy] # Copyright
  copy = "" # Empty for default content

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  clanky = "/clanky/:year/:month/:title/"
